package com.example.weingweing

open class Dong {
    var bh : HashMap<String, List<String>>
        get() = hashMapOf(
                "청운동" to listOf("청운효자동"),
                "신교동" to listOf("청운효자동"),
                "궁정동" to listOf("청운효자동"),
                "세종로" to listOf("청운효자동", "사직동"),
                "효자동" to listOf("청운효자동"),
                "창성동" to listOf("청운효자동"),
                "통인동" to listOf("청운효자동"),
                "누상동" to listOf("청운효자동"),
                "누하동" to listOf("청운효자동"),
                "옥인동" to listOf("청운효자동"),
                "사직동" to listOf("사직동"),
                "체부동" to listOf("사직동"),
                "필운동" to listOf("사직동"),
                "내자동" to listOf("사직동"),
                "통의동" to listOf("사직동"),
                "적선동" to listOf("사직동"),
                "도렴동" to listOf("사직동"),
                "당주동" to listOf("사직동"),
                "내수동" to listOf("사직동"),
                "신문로12가" to listOf("사직동"),
                "삼청동" to listOf("삼청동"),
                "팔판동" to listOf("삼청동"),
                "안국동" to listOf("삼청동"),
                "소격동" to listOf("삼청동"),
                "화동" to listOf("삼청동"),
                "사간동" to listOf("삼청동"),
                "송현동" to listOf("삼청동"),
                "부암동" to listOf("부암동"),
                "홍지동" to listOf("부암동"),
                "신영동" to listOf("부암동"),
                "평창동" to listOf("평창동"),
                "구기동" to listOf("평창동"),
                "무악동" to listOf("무악동"),
                "교남동" to listOf("교남동"),
                "평동" to listOf("교남동"),
                "송월동" to listOf("교남동"),
                "홍파동" to listOf("교남동"),
                "교북동" to listOf("교남동"),
                "행촌동" to listOf("교남동"),
                "가회동" to listOf("가회동"),
                "재동" to listOf("가회동"),
                "계동" to listOf("가회동"),
                "원서동" to listOf("가회동"),
                "종로1가" to listOf("종로1234가동"),
                "종로2가" to listOf("종로1234가동"),
                "종로3가" to listOf("종로1234가동"),
                "종로4가" to listOf("종로1234가동"),
                "청진동" to listOf("종로1234가동"),
                "서린동" to listOf("종로1234가동"),
                "수송동" to listOf("종로1234가동"),
                "중학동" to listOf("종로1234가동"),
                "공평동" to listOf("종로1234가동"),
                "관훈동" to listOf("종로1234가동"),
                "견지동" to listOf("종로1234가동"),
                "권농동" to listOf("종로1234가동"),
                "운니동" to listOf("종로1234가동"),
                "익선동" to listOf("종로1234가동"),
                "경운동" to listOf("종로1234가동"),
                "관철동" to listOf("종로1234가동"),
                "인사동" to listOf("종로1234가동"),
                "낙원동" to listOf("종로1234가동"),
                "와룡동" to listOf("종로1234가동"),
                "훈정동" to listOf("종로1234가동"),
                "묘동" to listOf("종로1234가동"),
                "봉익동" to listOf("종로1234가동"),
                "돈의동" to listOf("종로1234가동"),
                "장사동" to listOf("종로1234가동"),
                "관수동" to listOf("종로1234가동"),
                "인의동" to listOf("종로1234가동"),
                "예지동" to listOf("종로1234가동"),
                "원남동" to listOf("종로1234가동"),
                "종로5가" to listOf("종로56가동"),
                "종로6가" to listOf("종로56가동"),
                "효제동" to listOf("종로56가동"),
                "연지동" to listOf("종로56가동"),
                "충신동" to listOf("종로56가동"),
                "이화동" to listOf("이화동"),
                "연건동" to listOf("이화동"),
                "동숭동" to listOf("이화동"),
                "혜화동" to listOf("혜화동"),
                "명륜1가" to listOf("혜화동"),
                "명륜2가" to listOf("혜화동"),
                "명륜3가" to listOf("혜화동"),
                "명륜4가" to listOf("혜화동"),
                "창신동" to listOf("창신1동", "창신2동", "창신3동"),
                "숭인동" to listOf("숭인1동", "숭인2동"),
                "소공동" to listOf("소공동"),
                "북창동" to listOf("소공동"),
                "태평로2가" to listOf("소공동"),
                "남대문로2가" to listOf("소공동", "명동"),
                "남대문로3가" to listOf("소공동", "회현동"),
                "남대문로4가" to listOf("소공동", "회현동"),
                "서소문동" to listOf("소공동"),
                "정동" to listOf("소공동"),
                "순화동" to listOf("소공동", "회현동"),
                "의주로1가" to listOf("소공동"),
                "충정로1가" to listOf("소공동", "회현동"),
                "봉래동1가" to listOf("소공동", "회현동"),
                "회현동1가" to listOf("회현동", "명동"),
                "회현동2가" to listOf("회현동", "명동"),
                "남창동" to listOf("회현동"),
                "남대문로5가" to listOf("회현동"),
                "봉래동2가" to listOf("회현동"),
                "명동1가" to listOf("명동"),
                "명동2가" to listOf("명동"),
                "충무로1가" to listOf("명동"),
                "충무로2가" to listOf("명동"),
                "저동1가" to listOf("명동"),
                "남산동1가" to listOf("명동"),
                "남산동2가" to listOf("명동"),
                "남산동3가" to listOf("명동"),
                "태평로1가" to listOf("명동"),
                "무교동" to listOf("명동"),
                "다동" to listOf("명동"),
                "을지로1가" to listOf("명동"),
                "을지로2가" to listOf("명동"),
                "삼각동" to listOf("명동"),
                "남대문로1가" to listOf("명동"),
                "수하동" to listOf("명동"),
                "장교동" to listOf("명동"),
                "수표동" to listOf("명동"),
                "예장동" to listOf("명동", "필동"),
                "회현동3가" to listOf("명동"),
                "필동1가" to listOf("필동"),
                "필동2가" to listOf("필동"),
                "필동3가" to listOf("필동"),
                "남학동" to listOf("필동"),
                "주자동" to listOf("필동"),
                "충무로3가" to listOf("필동"),
                "충무로4가" to listOf("필동", "광희동"),
                "충무로5가" to listOf("필동", "광희동"),
                "장충동2가" to listOf("필동", "장충동"),
                "묵정동" to listOf("필동", "장충동"),
                "장충동1가" to listOf("장충동"),
                "광희동1가" to listOf("광희동"),
                "광희동2가" to listOf("광희동"),
                "쌍림동" to listOf("광희동"),
                "을지로6가" to listOf("광희동"),
                "을지로7가" to listOf("광희동"),
                "인헌동2가" to listOf("광희동"),
                "예관동" to listOf("광희동"),
                "오장동" to listOf("광희동"),
                "을지로3가" to listOf("을지로동"),
                "을지로4가" to listOf("을지로동"),
                "을지로5가" to listOf("을지로동"),
                "주교동" to listOf("을지로동"),
                "방산동" to listOf("을지로동"),
                "입정동" to listOf("을지로동"),
                "산림동" to listOf("을지로동"),
                "초동" to listOf("을지로동"),
                "인헌동1가" to listOf("을지로동"),
                "저동2가" to listOf("을지로동"),
                "무학동" to listOf("신당동"),
                "흥인동" to listOf("신당동"),
                "신당동" to listOf("신당동", "다산동", "약수동", "청구동", "신당5동", "동화동"),
                "황학동" to listOf("황학동"),
                "중림동" to listOf("중림동"),
                "의주로2가" to listOf("중림동"),
                "만리동1가" to listOf("중림동"),
                "후암동" to listOf("후암동"),
                "용산동2가" to listOf("용산2가동"),
                "용산동4가" to listOf("용산2가동"),
                "갈월동" to listOf("남영동"),
                "남영동" to listOf("남영동"),
                "동자동" to listOf("남영동"),
                "용산동1가" to listOf("남영동"),
                "청파동1가" to listOf("청파동"),
                "청파동2가" to listOf("청파동"),
                "청파동3가" to listOf("청파동"),
                "서계동" to listOf("청파동"),
                "원효로1가" to listOf("원효로1동"),
                "원효로2가" to listOf("원효로1동"),
                "문배동" to listOf("원효로1동"),
                "신계동" to listOf("원효로1동"),
                "원효로3가" to listOf("원효로2동"),
                "원효로4가" to listOf("원효로2동"),
                "신창동" to listOf("원효로2동"),
                "산천동" to listOf("원효로2동"),
                "청암동" to listOf("원효로2동"),
                "효창동" to listOf("효창동"),
                "용문동" to listOf("용문동"),
                "도원동" to listOf("용문동"),
                "한강로1가" to listOf("한강로동"),
                "한강로2가" to listOf("한강로동"),
                "한강로3가" to listOf("한강로동"),
                "용산동3가" to listOf("한강로동"),
                "용산동5가" to listOf("한강로동"),
                "이촌동" to listOf("이촌1동", "이촌2동"),
                "이태원동" to listOf("이태원1동", "이태원2동"),
                "한남동" to listOf("한남동"),
                "서빙고동" to listOf("서빙고동"),
                "동빙고동" to listOf("서빙고동"),
                "주성동" to listOf("서빙고동"),
                "용산동6가" to listOf("서빙고동"),
                "보광동" to listOf("보광동"),
                "하왕십리동" to listOf("왕십리2동", "왕십리도선동"),
                "상왕십리동" to listOf("왕십리도선동"),
                "도선동" to listOf("왕십리도선동"),
                "홍익동" to listOf("왕십리도선동"),
                "마장동" to listOf("마장동"),
                "사근동" to listOf("사근동"),
                "행당동" to listOf("사근동", "행당1동", "행당2동"),
                "응봉동" to listOf("응동동"),
                "금호동1가" to listOf("금호1가동"),
                "금호동2가" to listOf("금호2,3가동"),
                "금호동3가" to listOf("금호2,3가동"),
                "금호동4가" to listOf("금호4가동"),
                "옥수동" to listOf("옥수동"),
                "성수동1가" to listOf("성수1가1동", "성수1가2동"),
                "성수동2가" to listOf("성수2가1동", "聖水2街第3"),
                "송정동" to listOf("송정동", "용답동"),
                "용답동" to listOf("용답동"),
                "중곡동" to listOf("중곡1동", "중곡2동", "중곡3동", "중곡4동"),
                "능동" to listOf("능동"),
                "구의동" to listOf("구의1동", "구의2동", "구의3동"),
                "광장동" to listOf("광장동"),
                "자양동" to listOf("자양1동", "자양2동", "자양3동", "자양4동"),
                "화양동" to listOf("화양동"),
                "군자동" to listOf("군자동"),
                "신설동" to listOf("용신동"),
                "용두동" to listOf("용신동"),
                "제기동" to listOf("제기동"),
                "전농동" to listOf("전농1동", "전농2동"),
                "답십리동" to listOf("답십리1동", "답십리2동"),
                "장안동" to listOf("장안1동", "장안2동"),
                "청량리동" to listOf("청량리동"),
                "회기동" to listOf("회기동"),
                "휘경동" to listOf("휘경1동", "휘경2동"),
                "이문동" to listOf("이문1동", "이문2동"),
                "면목동" to listOf("면목본동", "면목2동", "면목38동", "면목4동", "면목5동", "면목7동"),
                "상봉동" to listOf("상봉1동", "상봉2동"),
                "중화동" to listOf("중화1동", "중화2동"),
                "묵동" to listOf("묵1동", "묵2동"),
                "망우동" to listOf("망우본동", "망우3동"),
                "신내동" to listOf("신내1동", "신내2동"),
                "성북동" to listOf("성북동"),
                "성북동1가" to listOf("성북동"),
                "동소문동1가" to listOf("성북동"),
                "동소문동4가" to listOf("성북동"),
                "삼선동1가" to listOf("삼선동"),
                "삼선동2가" to listOf("삼선동"),
                "삼선동3가" to listOf("삼선동"),
                "삼선동4가" to listOf("삼선동"),
                "삼선동5가" to listOf("삼선동"),
                "돈암동" to listOf("삼선동", "동선동", "돈암1동", "돈암2동", "정릉2동"),
                "동소문동2가" to listOf("삼선동"),
                "동소문동3가" to listOf("삼선동"),
                "동소문동5가" to listOf("삼선동"),
                "동선동1가" to listOf("동선동"),
                "동선동2가" to listOf("동선동"),
                "동선동3가" to listOf("동선동"),
                "동선동4가" to listOf("동선동"),
                "동선동5가" to listOf("동선동"),
                "동소문동6가" to listOf("동선동"),
                "동소문동7가" to listOf("동선동"),
                "안암동1가" to listOf("안암동"),
                "안암동2가" to listOf("안암동"),
                "안암동3가" to listOf("안암동"),
                "안암동4가" to listOf("안암동"),
                "안암동5가" to listOf("안암동"),
                "보문동1가" to listOf("보문동"),
                "보문동2가" to listOf("보문동"),
                "보문동3가" to listOf("보문동"),
                "보문동4가" to listOf("보문동"),
                "보문동5가" to listOf("보문동"),
                "보문동6가" to listOf("보문동"),
                "보문동7가" to listOf("보문동"),
                "정릉동" to listOf("정릉1동", "정릉2동", "정릉3동", "정릉4동"),
                "길음동" to listOf("길음1동", "길음2동"),
                "하월곡동" to listOf("길음2동", "월곡1동", "월곡2동"),
                "종암동" to listOf("종암동"),
                "상월곡동" to listOf("월곡2동"),
                "장위동" to listOf("장위1동", "장위2동", "장위3동"),
                "석관동" to listOf("석관동"),
                "미아동" to listOf("삼양동", "미아동", "송중동", "송천동", "삼각산동"),
                "번동" to listOf("번1동", "번2동", "번3동"),
                "수유동" to listOf("수유1동", "수유2동", "수유3동", "우이동", "인수동"),
                "우이동" to listOf("우이동"),
                "월계동" to listOf("월계1동", "월계2동", "월계3동"),
                "공릉동" to listOf("공릉1,3동", "공릉2동"),
                "하계동" to listOf("하계1동", "하계2동"),
                "중계동" to listOf("중계본동", "중계1동", "중계2,3동", "중계4동"),
                "상계동" to listOf(
                    "중계4동",
                    "상계1동",
                    "상계2동",
                    "상계3,4동",
                    "상계5동",
                    "상계6,7동",
                    "상계8동",
                    "상계9동",
                    "상계10동"
                ),
                "녹번동" to listOf("녹번동"),
                "불광동" to listOf("불광1동", "불광2동"),
                "갈현동" to listOf("갈현1동", "갈현2동", "구산동"),
                "구산동" to listOf("구산동"),
                "대조동" to listOf("대조동"),
                "응암동" to listOf("응암1동", "응암2동", "응암3동"),
                "역촌동" to listOf("역촌동"),
                "신사동" to listOf("신사1동", "신사2동", "신사동", "압구정동"),
                "증산동" to listOf("증산동"),
                "수색동" to listOf("수색동"),
                "진관동" to listOf("진관동"),
                "충정로2가" to listOf("충현동"),
                "충정로3가" to listOf("충현동"),
                "합동" to listOf("충현동"),
                "미근동" to listOf("충현동"),
                "북아현동" to listOf("충현동", "북아현동"),
                "천연동" to listOf("천연동"),
                "냉천동" to listOf("천연동"),
                "옥천동" to listOf("천연동"),
                "영천동" to listOf("천연동"),
                "현저동" to listOf("천연동"),
                "대신동" to listOf("신촌동"),
                "대현동" to listOf("신촌동"),
                "신촌동" to listOf("신촌동"),
                "봉원동" to listOf("신촌동"),
                "창천동" to listOf("신촌동"),
                "연희동" to listOf("연희동"),
                "홍제동" to listOf("홍제1동", "홍제2동", "홍제3동"),
                "홍은동" to listOf("홍은1동", "홍은2동"),
                "남가좌동" to listOf("남가좌1동", "남가좌2동"),
                "북가좌동" to listOf("북가좌1동", "북가좌2동"),
                "아현동" to listOf("아현동", "공덕동"),
                "공덕동" to listOf("아현동", "공덕동"),
                "염리동" to listOf("아현동", "용강동", "염리동"),
                "신공덕동" to listOf("공덕동"),
                "도화동" to listOf("공덕동", "도화동", "용강동"),
                "마포동" to listOf("도화동", "용강동"),
                "용강동" to listOf("용강동"),
                "토정동" to listOf("용강동"),
                "대흥동" to listOf("용강동", "대흥동", "신수동"),
                "신수동" to listOf("대흥동", "신수동"),
                "노고산동" to listOf("대흥동", "서교동"),
                "구수동" to listOf("신수동"),
                "현석동" to listOf("신수동"),
                "신정동" to listOf("신수동", "서강동", "신정1동", "신정2동", "신정3동", "신정4동", "신정6동", "신정7동"),
                "창전동" to listOf("서강동"),
                "상수동" to listOf("서강동"),
                "하중동" to listOf("서강동"),
                "당인동" to listOf("서강동"),
                "서교동" to listOf("서교동"),
                "동교동" to listOf("서교동"),
                "합정동" to listOf("합정동"),
                "망원동" to listOf("망원1동", "망원2동"),
                "연남동" to listOf("연남동"),
                "성산동" to listOf("성산1동", "성산2동"),
                "중동" to listOf("성산2동"),
                "상암동" to listOf("상암동"),
                "목동" to listOf("목1동", "목2동", "목3동", "목4동", "목5동"),
                "신월동" to listOf("신월1동", "신월2동", "신월3동", "신월4동", "신월5동", "신월6동", "신월7동"),
                "염창동" to listOf("염창동", "가양3동"),
                "등촌동" to listOf("등촌1동", "등촌2동", "등촌3동"),
                "화곡동" to listOf("화곡본동", "화곡1동", "화곡2동", "화곡3동", "화곡4동", "화곡6동", "화곡8동", "우장산동"),
                "내발산동" to listOf("우장산동", "발산1동"),
                "가양동" to listOf("가양1동", "가양2동", "가양3동"),
                "마곡동" to listOf("가양1동"),
                "외발산동" to listOf("발산1동"),
                "공항동" to listOf("공항동"),
                "과해동" to listOf("공항동"),
                "오곡동" to listOf("공항동"),
                "오쇠동" to listOf("공항동"),
                "방화동" to listOf("방화1동", "방화2동", "방화3동"),
                "개화동" to listOf("방화2동"),
                "신도림동" to listOf("신도림동"),
                "구로동" to listOf("구로1동", "구로2동", "구로3동", "구로4동", "구로5동"),
                "가리봉동" to listOf("가리봉동"),
                "고척동" to listOf("고척1동", "고척2동"),
                "개봉동" to listOf("개봉1동", "개봉2동", "개봉3동"),
                "오류동" to listOf("오류1동", "오류2동"),
                "천왕동" to listOf("오류2동"),
                "항동" to listOf("항동"),
                "온수동" to listOf("수궁동"),
                "궁동" to listOf("수궁동"),
                "가산동" to listOf("가산동"),
                "독산동" to listOf("독산1동", "독산2동", "독산3동", "독산4동"),
                "시흥동" to listOf("시흥1동", "시흥2동", "시흥3동", "시흥4동", "시흥5동"),
                "영등포동" to listOf("영등포본동"),
                "신길동" to listOf("영등포본동", "신길1동", "신길3동", "신길4동", "신길5동", "신길6동", "신길7동"),
                "영동포동1가" to listOf("영등포동"),
                "영동포동2가" to listOf("영등포동"),
                "영동포동3가" to listOf("영등포동"),
                "영동포동4가" to listOf("영등포동"),
                "영동포동5가" to listOf("영등포동"),
                "영동포동6가" to listOf("영등포동"),
                "영동포동7가" to listOf("영등포동"),
                "영동포동8가" to listOf("영등포동"),
                "영등포동" to listOf("영등포동"),
                "여의도동" to listOf("여의동"),
                "당산동1가" to listOf("당산1동"),
                "당산동2가" to listOf("당산1동"),
                "당산동3가" to listOf("당산1동"),
                "당산동4가" to listOf("당산2동"),
                "당산동5가" to listOf("당산2동"),
                "당산동6가" to listOf("당산2동"),
                "당산동" to listOf("당산2동"),
                "도림동" to listOf("도림동"),
                "문래동1가" to listOf("문래동"),
                "문래동2가" to listOf("문래동"),
                "문래동3가" to listOf("문래동"),
                "문래동4가" to listOf("문래동"),
                "문래동5가" to listOf("문래동"),
                "문래동6가" to listOf("문래동"),
                "양평동1가" to listOf("양평1동"),
                "양평동2가" to listOf("양평1동"),
                "양평동3가" to listOf("양평1동", "양평2동"),
                "양평동4가" to listOf("양평2동"),
                "양평동5가" to listOf("양평2동"),
                "양평동6가" to listOf("양평2동"),
                "양화동" to listOf("양평2동"),
                "양평동" to listOf("양평2동"),
                "대림동" to listOf("대림1동", "대림2동", "대림3동"),
                "노량진동" to listOf("노량진1동", "노량진2동"),
                "본동" to listOf("노량진1동"),
                "상도동" to listOf("상도1동", "상도2동", "상도3동", "상도4동"),
                "상도1동" to listOf("상도1동"),
                "흑석동" to listOf("흑석동"),
                "사당동" to listOf("사당1동", "사당2동", "사당3동", "사당4동", "사당5동"),
                "동작동" to listOf("사당2동"),
                "대방동" to listOf("대방동"),
                "신대방동" to listOf("신대방1동", "신대방2동"),
                "봉천동" to listOf("은천동", "성현동", "청룡동", "보라매", "청림동", "행운동", "낙성대동", "중앙동", "인헌동"),
                "남현동" to listOf("남현동"),
                "신림동" to listOf(
                    "서원동",
                    "신원동",
                    "서림동",
                    "난곡동",
                    "신사동",
                    "신림동",
                    "삼성동",
                    "난향동",
                    "조원동",
                    "대학동",
                    "미성동"
                ),
                "서초동" to listOf("서초1동", "서초2동", "서초3동", "서초4동"),
                "방배동" to listOf("서초3동", "방배본동", "방배1동", "방배2동", "방배3동", "방배4동"),
                "잠원동" to listOf("잠원동", "반포3동"),
                "반포동" to listOf("반포본동", "반포1동", "반포2동", "반포4동"),
                "양재동" to listOf("양재1동", "양재2동"),
                "우면동" to listOf("양재1동"),
                "원지동" to listOf("양재2동"),
                "내곡동" to listOf("내곡동"),
                "염곡동" to listOf("내곡동"),
                "신원동" to listOf("내곡동"),
                "압구정동" to listOf("신사동", "압구정동"),
                "논현동" to listOf("논현1동", "논현2동"),
                "청담동" to listOf("청담동"),
                "삼성동" to listOf("삼성1동", "삼성2동"),
                "대치동" to listOf("대치1동", "대치2동", "대치4동", "일원2동"),
                "역삼동" to listOf("역삼1동", "역삼2동"),
                "도곡동" to listOf("도곡1동", "도곡2동"),
                "개포동" to listOf("개포1동", "개포2동", "개포4동", "일원2동"),
                "일원동" to listOf("일원본동", "일원1동", "일원2동"),
                "수서동" to listOf("일원본동", "일원1동", "수서동"),
                "세곡동" to listOf("세곡동"),
                "자곡동" to listOf("세곡동"),
                "율현동" to listOf("세곡동"),
                "풍납동" to listOf("풍납1동", "풍납2동"),
                "거여동" to listOf("거여1동", "거여2동", "위례동"),
                "마천동" to listOf("마천1동", "마천2동"),
                "방이동" to listOf("방이1동", "방이2동", "오륜동"),
                "오금동" to listOf("오금동"),
                "송파동" to listOf("송파1동", "송파2동"),
                "석촌동" to listOf("석촌동"),
                "삼전동" to listOf("삼전동"),
                "가락동" to listOf("가락본동", "가락1동", "가락2동"),
                "문정동" to listOf("문정1동", "문정2동", "장지동"),
                "장지동" to listOf("문정2동", "장지동", "위례동"),
                "잠실동" to listOf("잠실본동", "잠실2동", "잠실3동", "잠실7동"),
                "신천동" to listOf("잠실4동", "잠실6동"),
                "강일동" to listOf("강일동"),
                "상일동" to listOf("강일동", "상일동"),
                "명일동" to listOf("명일1동", "명일2동"),
                "고덕동" to listOf("고덕1동", "고덕2동"),
                "암사동" to listOf("암사1동", "암사2동", "암사3동"),
                "천호동" to listOf("천호1동", "천호2동", "천호3동"),
                "성내동" to listOf("성내1동", "성내2동", "성내3동"),
                "길동" to listOf("길동"),
                "둔촌동" to listOf("둔촌1동", "둔촌2동")
            )
        set(value) = TODO()

    var hb : HashMap<String, List<String>>  = hashMapOf(
        "청운효자동" to listOf("청운동", "신교동", "궁정동", "세종로", "효자동", "창성동", "통인동", "누상동", "누하동", "옥인동"),
        "사직동" to listOf(
            "사직동",
            "체부동",
            "필운동",
            "내자동",
            "통의동",
            "적선동",
            "세종로",
            "도렴동",
            "당주동",
            "내수동",
            "신문로12가"
        ),
        "삼청동" to listOf("삼청동", "팔판동", "안국동", "소격동", "화동", "사간동", "송현동"),
        "부암동" to listOf("부암동", "홍지동", "신영동"),
        "평창동" to listOf("평창동", "구기동"),
        "무악동" to listOf("무악동"),
        "교남동" to listOf("교남동", "평동", "송월동", "홍파동", "교북동", "행촌동"),
        "가회동" to listOf("가회동", "재동", "계동", "원서동"),
        "종로1234가동" to listOf(
            "종로1가",
            "종로2가",
            "종로3가",
            "종로4가",
            "청진동",
            "서린동",
            "수송동",
            "중학동",
            "공평동",
            "관훈동",
            "견지동",
            "권농동",
            "운니동",
            "익선동",
            "경운동",
            "관철동",
            "인사동",
            "낙원동",
            "와룡동",
            "훈정동",
            "묘동",
            "봉익동",
            "돈의동",
            "장사동",
            "관수동",
            "인의동",
            "예지동",
            "원남동"
        ),
        "종로56가동" to listOf("종로5가", "종로6가", "효제동", "연지동", "충신동"),
        "이화동" to listOf("이화동", "연건동", "동숭동"),
        "혜화동" to listOf("혜화동", "명륜1가", "명륜2가", "명륜3가", "명륜4가"),
        "창신1동" to listOf("창신동"),
        "창신2동" to listOf("창신동"),
        "창신3동" to listOf("창신동"),
        "숭인1동" to listOf("숭인동"),
        "숭인2동" to listOf("숭인동"),
        "소공동" to listOf(
            "소공동",
            "북창동",
            "태평로2가",
            "남대문로2가",
            "남대문로3가",
            "남대문로4가",
            "서소문동",
            "정동",
            "순화동",
            "의주로1가",
            "충정로1가",
            "봉래동1가"
        ),
        "회현동" to listOf(
            "회현동1가",
            "회현동2가",
            "남창동",
            "남대문로3가",
            "남대문로4가",
            "남대문로5가",
            "봉래동1가",
            "봉래동2가",
            "충정로1가",
            "순화동"
        ),
        "명동" to listOf(
            "명동1가",
            "명동2가",
            "충무로1가",
            "충무로2가",
            "저동1가",
            "남산동1가",
            "남산동2가",
            "남산동3가",
            "태평로1가",
            "무교동",
            "다동",
            "을지로1가",
            "을지로2가",
            "삼각동",
            "남대문로1가",
            "남대문로2가",
            "수하동",
            "장교동",
            "수표동",
            "예장동",
            "회현동1가",
            "회현동2가",
            "회현동3가"
        ),
        "필동" to listOf(
            "필동1가",
            "필동2가",
            "필동3가",
            "남학동",
            "주자동",
            "예장동",
            "충무로3가",
            "충무로4가",
            "충무로5가",
            "장충동2가",
            "묵정동"
        ),
        "장충동" to listOf("장충동1가", "장충동2가", "묵정동"),
        "광희동" to listOf(
            "광희동1가",
            "광희동2가",
            "쌍림동",
            "을지로6가",
            "을지로7가",
            "충무로4가",
            "충무로5가",
            "인헌동2가",
            "예관동",
            "오장동"
        ),
        "을지로동" to listOf(
            "을지로3가",
            "을지로4가",
            "을지로5가",
            "주교동",
            "방산동",
            "입정동",
            "산림동",
            "초동",
            "인헌동1가",
            "저동2가"
        ),
        "신당동" to listOf("무학동", "흥인동", "신당동"),
        "다산동" to listOf("신당동"),
        "약수동" to listOf("신당동"),
        "청구동" to listOf("신당동"),
        "신당5동" to listOf("신당동"),
        "동화동" to listOf("신당동"),
        "황학동" to listOf("황학동"),
        "중림동" to listOf("중림동", "의주로2가", "만리동1가"),
        "후암동" to listOf("후암동"),
        "용산2가동" to listOf("용산동2가", "용산동4가"),
        "남영동" to listOf("갈월동", "남영동", "동자동", "용산동1가"),
        "청파동" to listOf("청파동1가", "청파동2가", "청파동3가", "서계동"),
        "원효로1동" to listOf("원효로1가", "원효로2가", "문배동", "신계동"),
        "원효로2동" to listOf("원효로3가", "원효로4가", "신창동", "산천동", "청암동"),
        "효창동" to listOf("효창동"),
        "용문동" to listOf("용문동", "도원동"),
        "한강로동" to listOf("한강로1가", "한강로2가", "한강로3가", "용산동3가", "용산동5가"),
        "이촌1동" to listOf("이촌동"),
        "이촌2동" to listOf("이촌동"),
        "이태원1동" to listOf("이태원동"),
        "이태원2동" to listOf("이태원동"),
        "한남동" to listOf("한남동"),
        "서빙고동" to listOf("서빙고동", "동빙고동", "주성동", "용산동6가"),
        "보광동" to listOf("보광동"),
        "왕십리2동" to listOf("하왕십리동"),
        "왕십리도선동" to listOf("상왕십리동", "하왕십리동", "도선동", "홍익동"),
        "마장동" to listOf("마장동"),
        "사근동" to listOf("사근동", "행당동"),
        "행당1동" to listOf("행당동"),
        "행당2동" to listOf("행당동"),
        "응동동" to listOf("응봉동"),
        "금호1가동" to listOf("금호동1가"),
        "금호2,3가동" to listOf("금호동2가", "금호동3가"),
        "금호4가동" to listOf("금호동4가"),
        "옥수동" to listOf("옥수동"),
        "성수1가1동" to listOf("성수동1가"),
        "성수1가2동" to listOf("성수동1가"),
        "성수2가1동" to listOf("성수동2가"),
        "송정동" to listOf("송정동"),
        "용답동" to listOf("용답동", "송정동"),
        "중곡1동" to listOf("중곡동"),
        "중곡2동" to listOf("중곡동"),
        "중곡3동" to listOf("중곡동"),
        "중곡4동" to listOf("중곡동"),
        "능동" to listOf("능동"),
        "구의1동" to listOf("구의동"),
        "구의2동" to listOf("구의동"),
        "구의3동" to listOf("구의동"),
        "광장동" to listOf("광장동"),
        "자양1동" to listOf("자양동"),
        "자양2동" to listOf("자양동"),
        "자양3동" to listOf("자양동"),
        "자양4동" to listOf("자양동"),
        "화양동" to listOf("화양동"),
        "군자동" to listOf("군자동"),
        "용신동" to listOf("신설동", "용두동"),
        "제기동" to listOf("제기동"),
        "전농1동" to listOf("전농동"),
        "전농2동" to listOf("전농동"),
        "답십리1동" to listOf("답십리동"),
        "답십리2동" to listOf("답십리동"),
        "장안1동" to listOf("장안동"),
        "장안2동" to listOf("장안동"),
        "청량리동" to listOf("청량리동"),
        "회기동" to listOf("회기동"),
        "휘경1동" to listOf("휘경동"),
        "휘경2동" to listOf("휘경동"),
        "이문1동" to listOf("이문동"),
        "이문2동" to listOf("이문동"),
        "면목본동" to listOf("면목동"),
        "면목2동" to listOf("면목동"),
        "면목38동" to listOf("면목동"),
        "면목4동" to listOf("면목동"),
        "면목5동" to listOf("면목동"),
        "면목7동" to listOf("면목동"),
        "상봉1동" to listOf("상봉동"),
        "상봉2동" to listOf("상봉동"),
        "중화1동" to listOf("중화동"),
        "중화2동" to listOf("중화동"),
        "묵1동" to listOf("묵동"),
        "묵2동" to listOf("묵동"),
        "망우본동" to listOf("망우동"),
        "망우3동" to listOf("망우동"),
        "신내1동" to listOf("신내동"),
        "신내2동" to listOf("신내동"),
        "성북동" to listOf("성북동", "성북동1가", "동소문동1가", "동소문동4가"),
        "삼선동" to listOf(
            "삼선동1가",
            "삼선동2가",
            "삼선동3가",
            "삼선동4가",
            "삼선동5가",
            "돈암동",
            "동소문동2가",
            "동소문동3가",
            "동소문동5가"
        ),
        "동선동" to listOf("동선동1가", "동선동2가", "동선동3가", "동선동4가", "동선동5가", "돈암동", "동소문동6가", "동소문동7가"),
        "돈암1동" to listOf("돈암동"),
        "돈암2동" to listOf("돈암동"),
        "안암동" to listOf("안암동1가", "안암동2가", "안암동3가", "안암동4가", "안암동5가"),
        "보문동" to listOf("보문동1가", "보문동2가", "보문동3가", "보문동4가", "보문동5가", "보문동6가", "보문동7가"),
        "정릉1동" to listOf("정릉동"),
        "정릉2동" to listOf("정릉동", "돈암동"),
        "정릉3동" to listOf("정릉동"),
        "정릉4동" to listOf("정릉동"),
        "길음1동" to listOf("길음동"),
        "길음2동" to listOf("길음동", "하월곡동"),
        "종암동" to listOf("종암동"),
        "월곡1동" to listOf("하월곡동"),
        "월곡2동" to listOf("하월곡동", "상월곡동"),
        "장위1동" to listOf("장위동"),
        "장위2동" to listOf("장위동"),
        "장위3동" to listOf("장위동"),
        "석관동" to listOf("석관동"),
        "삼양동" to listOf("미아동"),
        "미아동" to listOf("미아동"),
        "송중동" to listOf("미아동"),
        "송천동" to listOf("미아동"),
        "삼각산동" to listOf("미아동"),
        "번1동" to listOf("번동"),
        "번2동" to listOf("번동"),
        "번3동" to listOf("번동"),
        "수유1동" to listOf("수유동"),
        "수유2동" to listOf("수유동"),
        "수유3동" to listOf("수유동"),
        "우이동" to listOf("우이동", "수유동"),
        "인수동" to listOf("수유동"),
        "월계1동" to listOf("월계동"),
        "월계2동" to listOf("월계동"),
        "월계3동" to listOf("월계동"),
        "공릉1,3동" to listOf("공릉동"),
        "공릉2동" to listOf("공릉동"),
        "하계1동" to listOf("하계동"),
        "하계2동" to listOf("하계동"),
        "중계본동" to listOf("중계동"),
        "중계1동" to listOf("중계동"),
        "중계2,3동" to listOf("중계동"),
        "중계4동" to listOf("중계동", "상계동"),
        "상계1동" to listOf("상계동"),
        "상계2동" to listOf("상계동"),
        "상계3,4동" to listOf("상계동"),
        "상계5동" to listOf("상계동"),
        "상계6,7동" to listOf("상계동"),
        "상계8동" to listOf("상계동"),
        "상계9동" to listOf("상계동"),
        "상계10동" to listOf("상계동"),
        "녹번동" to listOf("녹번동"),
        "불광1동" to listOf("불광동"),
        "불광2동" to listOf("불광동"),
        "갈현1동" to listOf("갈현동"),
        "갈현2동" to listOf("갈현동"),
        "구산동" to listOf("구산동", "갈현동"),
        "대조동" to listOf("대조동"),
        "응암1동" to listOf("응암동"),
        "응암2동" to listOf("응암동"),
        "응암3동" to listOf("응암동"),
        "역촌동" to listOf("역촌동"),
        "신사1동" to listOf("신사동"),
        "신사2동" to listOf("신사동"),
        "증산동" to listOf("증산동"),
        "수색동" to listOf("수색동"),
        "진관동" to listOf("진관동"),
        "충현동" to listOf("충정로2가", "충정로3가", "합동", "미근동", "북아현동"),
        "천연동" to listOf("천연동", "냉천동", "옥천동", "영천동", "현저동"),
        "북아현동" to listOf("북아현동"),
        "신촌동" to listOf("대신동", "대현동", "신촌동", "봉원동", "창천동"),
        "연희동" to listOf("연희동"),
        "홍제1동" to listOf("홍제동"),
        "홍제2동" to listOf("홍제동"),
        "홍제3동" to listOf("홍제동"),
        "홍은1동" to listOf("홍은동"),
        "홍은2동" to listOf("홍은동"),
        "남가좌1동" to listOf("남가좌동"),
        "남가좌2동" to listOf("남가좌동"),
        "북가좌1동" to listOf("북가좌동"),
        "북가좌2동" to listOf("북가좌동"),
        "아현동" to listOf("아현동", "공덕동", "염리동"),
        "공덕동" to listOf("공덕동", "아현동", "신공덕동", "도화동"),
        "도화동" to listOf("도화동", "마포동"),
        "용강동" to listOf("용강동", "도화동", "토정동", "염리동", "마포동", "대흥동"),
        "대흥동" to listOf("대흥동", "신수동", "노고산동"),
        "염리동" to listOf("염리동"),
        "신수동" to listOf("신수동", "구수동", "현석동", "신정동", "대흥동"),
        "서강동" to listOf("창전동", "상수동", "하중동", "신정동", "당인동"),
        "서교동" to listOf("서교동", "노고산동", "동교동"),
        "합정동" to listOf("합정동"),
        "망원1동" to listOf("망원동"),
        "망원2동" to listOf("망원동"),
        "연남동" to listOf("연남동"),
        "성산1동" to listOf("성산동"),
        "성산2동" to listOf("성산동", "중동"),
        "상암동" to listOf("상암동"),
        "목1동" to listOf("목동"),
        "목2동" to listOf("목동"),
        "목3동" to listOf("목동"),
        "목4동" to listOf("목동"),
        "목5동" to listOf("목동"),
        "신월1동" to listOf("신월동"),
        "신월2동" to listOf("신월동"),
        "신월3동" to listOf("신월동"),
        "신월4동" to listOf("신월동"),
        "신월5동" to listOf("신월동"),
        "신월6동" to listOf("신월동"),
        "신월7동" to listOf("신월동"),
        "신정1동" to listOf("신정동"),
        "신정2동" to listOf("신정동"),
        "신정3동" to listOf("신정동"),
        "신정4동" to listOf("신정동"),
        "신정6동" to listOf("신정동"),
        "신정7동" to listOf("신정동"),
        "염창동" to listOf("염창동"),
        "등촌1동" to listOf("등촌동"),
        "등촌2동" to listOf("등촌동"),
        "등촌3동" to listOf("등촌동"),
        "화곡본동" to listOf("화곡동"),
        "화곡1동" to listOf("화곡동"),
        "화곡2동" to listOf("화곡동"),
        "화곡3동" to listOf("화곡동"),
        "화곡4동" to listOf("화곡동"),
        "화곡6동" to listOf("화곡동"),
        "화곡8동" to listOf("화곡동"),
        "우장산동" to listOf("화곡동", "내발산동"),
        "가양1동" to listOf("가양동", "마곡동"),
        "가양2동" to listOf("가양동"),
        "가양3동" to listOf("가양동", "염창동"),
        "발산1동" to listOf("내발산동", "외발산동"),
        "공항동" to listOf("공항동", "과해동", "오곡동", "오쇠동"),
        "방화1동" to listOf("방화동"),
        "방화2동" to listOf("방화동", "개화동"),
        "방화3동" to listOf("방화동"),
        "신도림동" to listOf("신도림동"),
        "구로1동" to listOf("구로동"),
        "구로2동" to listOf("구로동"),
        "구로3동" to listOf("구로동"),
        "구로4동" to listOf("구로동"),
        "구로5동" to listOf("구로동"),
        "가리봉동" to listOf("가리봉동"),
        "고척1동" to listOf("고척동"),
        "고척2동" to listOf("고척동"),
        "개봉1동" to listOf("개봉동"),
        "개봉2동" to listOf("개봉동"),
        "개봉3동" to listOf("개봉동"),
        "오류1동" to listOf("오류동"),
        "오류2동" to listOf("오류동", "천왕동"),
        "항동" to listOf("항동"),
        "수궁동" to listOf("온수동", "궁동"),
        "가산동" to listOf("가산동"),
        "독산1동" to listOf("독산동"),
        "독산2동" to listOf("독산동"),
        "독산3동" to listOf("독산동"),
        "독산4동" to listOf("독산동"),
        "시흥1동" to listOf("시흥동"),
        "시흥2동" to listOf("시흥동"),
        "시흥3동" to listOf("시흥동"),
        "시흥4동" to listOf("시흥동"),
        "시흥5동" to listOf("시흥동"),
        "영등포본동" to listOf("영등포동", "신길동"),
        "영등포동" to listOf(
            "영동포동1가",
            "영동포동2가",
            "영동포동3가",
            "영동포동4가",
            "영동포동5가",
            "영동포동6가",
            "영동포동7가",
            "영동포동8가",
            ""
        ),
        "여의동" to listOf("여의도동"),
        "당산1동" to listOf("당산동1가", "당산동2가", "당산동3가"),
        "당산2동" to listOf("당산동4가", "당산동5가", "당산동6가", "당산동"),
        "도림동" to listOf("도림동"),
        "문래동" to listOf("문래동1가", "문래동2가", "문래동3가", "문래동4가", "문래동5가", "문래동6가"),
        "양평1동" to listOf("양평동1가", "양평동2가", "양평동3가"),
        "양평2동" to listOf("양평동3가", "양평동4가", "양평동5가", "양평동6가", "양화동", "양평동"),
        "신길1동" to listOf("신길동"),
        "신길3동" to listOf("신길동"),
        "신길4동" to listOf("신길동"),
        "신길5동" to listOf("신길동"),
        "신길6동" to listOf("신길동"),
        "신길7동" to listOf("신길동"),
        "대림1동" to listOf("대림동"),
        "대림2동" to listOf("대림동"),
        "대림3동" to listOf("대림동"),
        "노량진1동" to listOf("노량진동", "본동"),
        "노량진2동" to listOf("노량진동"),
        "상도1동" to listOf("상도동", "상도1동"),
        "상도2동" to listOf("상도동"),
        "상도3동" to listOf("상도동"),
        "상도4동" to listOf("상도동"),
        "흑석동" to listOf("흑석동"),
        "사당1동" to listOf("사당동"),
        "사당2동" to listOf("사당동", "동작동"),
        "사당3동" to listOf("사당동"),
        "사당4동" to listOf("사당동"),
        "사당5동" to listOf("사당동"),
        "대방동" to listOf("대방동"),
        "신대방1동" to listOf("신대방동"),
        "신대방2동" to listOf("신대방동"),
        "은천동" to listOf("봉천동"),
        "성현동" to listOf("봉천동"),
        "청룡동" to listOf("봉천동"),
        "보라매" to listOf("봉천동"),
        "청림동" to listOf("봉천동"),
        "행운동" to listOf("봉천동"),
        "낙성대동" to listOf("봉천동"),
        "중앙동" to listOf("봉천동"),
        "인헌동" to listOf("봉천동"),
        "남현동" to listOf("남현동"),
        "서원동" to listOf("신림동"),
        "신원동" to listOf("신림동"),
        "서림동" to listOf("신림동"),
        "난곡동" to listOf("신림동"),
        "신사동" to listOf("신림동", "신사동", "압구정동"),
        "신림동" to listOf("신림동"),
        "삼성동" to listOf("신림동"),
        "난향동" to listOf("신림동"),
        "조원동" to listOf("신림동"),
        "대학동" to listOf("신림동"),
        "미성동" to listOf("신림동"),
        "서초1동" to listOf("서초동"),
        "서초2동" to listOf("서초동"),
        "서초3동" to listOf("서초동", "방배동"),
        "서초4동" to listOf("서초동"),
        "잠원동" to listOf("잠원동"),
        "반포본동" to listOf("반포동"),
        "반포1동" to listOf("반포동"),
        "반포2동" to listOf("반포동"),
        "반포3동" to listOf("잠원동"),
        "반포4동" to listOf("반포동"),
        "방배본동" to listOf("방배동"),
        "방배1동" to listOf("방배동"),
        "방배2동" to listOf("방배동"),
        "방배3동" to listOf("방배동"),
        "방배4동" to listOf("방배동"),
        "양재1동" to listOf("양재동", "우면동"),
        "양재2동" to listOf("양재동", "원지동"),
        "내곡동" to listOf("내곡동", "염곡동", "신원동"),
        "논현1동" to listOf("논현동"),
        "논현2동" to listOf("논현동"),
        "압구정동" to listOf("압구정동", "신사동"),
        "청담동" to listOf("청담동"),
        "삼성1동" to listOf("삼성동"),
        "삼성2동" to listOf("삼성동"),
        "대치1동" to listOf("대치동"),
        "대치2동" to listOf("대치동"),
        "대치4동" to listOf("대치동"),
        "역삼1동" to listOf("역삼동"),
        "역삼2동" to listOf("역삼동"),
        "도곡1동" to listOf("도곡동"),
        "도곡2동" to listOf("도곡동"),
        "개포1동" to listOf("개포동"),
        "개포2동" to listOf("개포동"),
        "개포4동" to listOf("개포동"),
        "일원본동" to listOf("일원동", "수서동"),
        "일원1동" to listOf("일원동", "수서동"),
        "일원2동" to listOf("일원동", "대치동", "개포동"),
        "수서동" to listOf("수서동"),
        "세곡동" to listOf("세곡동", "자곡동", "율현동"),
        "풍납1동" to listOf("풍납동"),
        "풍납2동" to listOf("풍납동"),
        "거여1동" to listOf("거여동"),
        "거여2동" to listOf("거여동"),
        "마천1동" to listOf("마천동"),
        "마천2동" to listOf("마천동"),
        "방이1동" to listOf("방이동"),
        "방이2동" to listOf("방이동"),
        "오륜동" to listOf("방이동"),
        "오금동" to listOf("오금동"),
        "송파1동" to listOf("송파동"),
        "송파2동" to listOf("송파동"),
        "석촌동" to listOf("석촌동"),
        "삼전동" to listOf("삼전동"),
        "가락본동" to listOf("가락동"),
        "가락1동" to listOf("가락동"),
        "가락2동" to listOf("가락동"),
        "문정1동" to listOf("문정동"),
        "문정2동" to listOf("문정동", "장지동"),
        "장지동" to listOf("장지동", "문정동"),
        "위례동" to listOf("장지동", "거여동"),
        "잠실본동" to listOf("잠실동"),
        "잠실2동" to listOf("잠실동"),
        "잠실3동" to listOf("잠실동"),
        "잠실4동" to listOf("신천동"),
        "잠실6동" to listOf("신천동"),
        "잠실7동" to listOf("잠실동"),
        "강일동" to listOf("강일동", "상일동"),
        "상일동" to listOf("상일동"),
        "명일1동" to listOf("명일동"),
        "명일2동" to listOf("명일동"),
        "고덕1동" to listOf("고덕동"),
        "고덕2동" to listOf("고덕동"),
        "암사1동" to listOf("암사동"),
        "암사2동" to listOf("암사동"),
        "암사3동" to listOf("암사동"),
        "천호1동" to listOf("천호동"),
        "천호2동" to listOf("천호동"),
        "천호3동" to listOf("천호동"),
        "성내1동" to listOf("성내동"),
        "성내2동" to listOf("성내동"),
        "성내3동" to listOf("성내동"),
        "길동" to listOf("길동"),
        "둔촌1동" to listOf("둔촌동"),
        "둔촌2동" to listOf("둔촌동")
        )
}